### ISSUE TITLE
FieldType.OBJECT类型的字段处理性能很差

### ISSUE THREAD

**Issue by Reedman** [jhunters/jprotobuf#100]
对象包含单个嵌套的FieldType.OBJECT类型字段，10000个对象，序列化需要4-5秒，反序需要2-3秒。有没有优化办法？

**Comment by xiemalin** [comment]
把示例代码发一下上来，我们来分析定位一下原因

**Comment by Reedman** [comment]
> 把示例代码发一下上来，我们来分析定位一下原因

package com.ctrip.hotel.intl.pricing.shadow.job.data;

import com.baidu.bjf.remoting.protobuf.FieldType;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;

import java.util.List;

@ProtobufClass
public class Company {

    @Protobuf(fieldType = FieldType.STRING, order = 1, required = true)
    private String name;

    @Protobuf(fieldType = FieldType.OBJECT, order = 2)
    private List<Employee> employees;

    @Protobuf(fieldType = FieldType.DOUBLE, order = 3)
    private Double age;

    @Protobuf(fieldType = FieldType.INT32, order = 4)
    private Integer headCount;

    @Protobuf(fieldType = FieldType.INT32, order = 5)
    private List<Integer> subIds;

    @Protobuf(fieldType = FieldType.OBJECT, order = 6)
    private Employee ceo;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Employee> getEmployees() {
        return employees;
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }

    public Double getAge() {
        return age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    public Integer getHeadCount() {
        return headCount;
    }

    public void setHeadCount(Integer headCount) {
        this.headCount = headCount;
    }

    public List<Integer> getSubIds() {
        return subIds;
    }

    public void setSubIds(List<Integer> subIds) {
        this.subIds = subIds;
    }

    public Employee getCeo() {
        return ceo;
    }

    public void setCeo(Employee ceo) {
        this.ceo = ceo;
    }
}


package com.ctrip.hotel.intl.pricing.shadow.job.data;

import com.baidu.bjf.remoting.protobuf.FieldType;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;

@ProtobufClass
public class Employee {

    @Protobuf(fieldType = FieldType.STRING, order = 1, required = true)
    private String name;

    @Protobuf(fieldType = FieldType.INT32, order = 2, required = true)
    private Integer age;

    @Protobuf(fieldType = FieldType.DOUBLE, order = 3, required = true)
    private Double salary;

    @Protobuf(fieldType = FieldType.BOOL, order = 4, required = true)
    private Boolean valid;

    public Employee(String name, Integer age, Double salary, Boolean valid) {
        this.name = name;
        this.age = age;
        this.salary = salary;
        this.valid = valid;
    }

    public Employee() {}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Double getSalary() {
        return salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public Boolean getValid() {
        return valid;
    }

    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}


package com.ctrip.hotel.intl.pricing.shadow.job;

import com.baidu.bjf.remoting.protobuf.Codec;
import com.baidu.bjf.remoting.protobuf.FieldType;
import com.baidu.bjf.remoting.protobuf.ProtobufProxy;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.ctrip.hotel.intl.pricing.Application;
import com.ctrip.hotel.intl.pricing.entity.htlofflineanalysisdb.Intlibushadowdefaultaddprice;
import com.ctrip.hotel.intl.pricing.shadow.job.data.Company;
import com.ctrip.hotel.intl.pricing.shadow.job.data.Employee;
import javafx.beans.binding.LongExpression;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.support.AnnotationConfigContextLoader;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.*;

/**
 * ProtoBuf Sample
 * See https://github.com/jhunters/jprotobuf/blob/master/README.md
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = Application.class, loader = AnnotationConfigContextLoader.class)
public class JProtoBufTest {

    private Company company;

    @Before
    public void setUp() throws Exception {
        company = new Company();
        company.setName("Company");
        company.setAge(20d);
        company.setHeadCount(10000);
        List<Employee> employees = new ArrayList<>();

        Random r = new Random();
        int size = 200;
        List<Integer> integers = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            integers.add(r.nextInt());
        }

        company.setSubIds(integers);
        //employees.add(new Employee("Jone Doe", 30, 1000d, false));
        //employees.add(new Employee("Mary Suu", 26, 2000d, true));

        company.setEmployees(employees);
        company.setCeo(new Employee("Tom Hawk", 55, 1d, true));

    }

    @After
    public void tearDown() throws Exception {

    }

    @Test
    public void serializeTest() throws IOException {

        long start = System.currentTimeMillis();

        Codec<Company> dompanyCodec = ProtobufProxy.create(Company.class);
        //Codec<Employee> employeeCodec = ProtobufProxy.create(Employee.class);

        System.out.print(String.format("Compile time elapsed: %d\n", System.currentTimeMillis() - start));

        // 序列化测试
        start = System.currentTimeMillis();
        int loop = 10000;
        while(loop-- > 0) {

            byte[] bb = dompanyCodec.encode(company);
        }
        System.out.print(String.format("Encode for 10000 times elapsed: %d\n", System.currentTimeMillis() - start));

        // 反序测试
        start = System.currentTimeMillis();
        loop = 10000;
        byte[] bytes = dompanyCodec.encode(company);
        while (loop-- > 0) {
            // 反序
            Company company = dompanyCodec.decode(bytes);
        }
        System.out.print(String.format("Decode for 10000 times elapsed: %d\n", System.currentTimeMillis() - start));
    }
}

**Comment by Reedman** [comment]
import com.baidu.bjf.remoting.protobuf.FieldType;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;

import java.util.List;

@ProtobufClass
public class Company {

    @Protobuf(fieldType = FieldType.STRING, order = 1, required = true)
    private String name;

    @Protobuf(fieldType = FieldType.OBJECT, order = 2)
    private List<Employee> employees;

    @Protobuf(fieldType = FieldType.DOUBLE, order = 3)
    private Double age;

    @Protobuf(fieldType = FieldType.INT32, order = 4)
    private Integer headCount;

    @Protobuf(fieldType = FieldType.INT32, order = 5)
    private List<Integer> subIds;

    @Protobuf(fieldType = FieldType.OBJECT, order = 6)
    private Employee ceo;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Employee> getEmployees() {
        return employees;
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }

    public Double getAge() {
        return age;
    }

    public void setAge(Double age) {
        this.age = age;
    }

    public Integer getHeadCount() {
        return headCount;
    }

    public void setHeadCount(Integer headCount) {
        this.headCount = headCount;
    }

    public List<Integer> getSubIds() {
        return subIds;
    }

    public void setSubIds(List<Integer> subIds) {
        this.subIds = subIds;
    }

    public Employee getCeo() {
        return ceo;
    }

    public void setCeo(Employee ceo) {
        this.ceo = ceo;
    }
}


import com.baidu.bjf.remoting.protobuf.FieldType;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;

@ProtobufClass
public class Employee {

    @Protobuf(fieldType = FieldType.STRING, order = 1, required = true)
    private String name;

    @Protobuf(fieldType = FieldType.INT32, order = 2, required = true)
    private Integer age;

    @Protobuf(fieldType = FieldType.DOUBLE, order = 3, required = true)
    private Double salary;

    @Protobuf(fieldType = FieldType.BOOL, order = 4, required = true)
    private Boolean valid;

    public Employee(String name, Integer age, Double salary, Boolean valid) {
        this.name = name;
        this.age = age;
        this.salary = salary;
        this.valid = valid;
    }

    public Employee() {}

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Double getSalary() {
        return salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public Boolean getValid() {
        return valid;
    }

    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}


/**
 * ProtoBuf Sample
 * See https://github.com/jhunters/jprotobuf/blob/master/README.md
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = Application.class, loader = AnnotationConfigContextLoader.class)
public class JProtoBufTest {

    private Company company;

    @Before
    public void setUp() throws Exception {
        company = new Company();
        company.setName("Company");
        company.setAge(20d);
        company.setHeadCount(10000);
        List<Employee> employees = new ArrayList<>();

        Random r = new Random();
        int size = 200;
        List<Integer> integers = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            integers.add(r.nextInt());
        }

        company.setSubIds(integers);
        //employees.add(new Employee("Jone Doe", 30, 1000d, false));
        //employees.add(new Employee("Mary Suu", 26, 2000d, true));

        company.setEmployees(employees);
        company.setCeo(new Employee("Tom Hawk", 55, 1d, true));

    }

    @After
    public void tearDown() throws Exception {

    }

    @Test
    public void serializeTest() throws IOException {

        long start = System.currentTimeMillis();

        Codec<Company> dompanyCodec = ProtobufProxy.create(Company.class);
        //Codec<Employee> employeeCodec = ProtobufProxy.create(Employee.class);

        System.out.print(String.format("Compile time elapsed: %d\n", System.currentTimeMillis() - start));

        // 序列化测试
        start = System.currentTimeMillis();
        int loop = 10000;
        while(loop-- > 0) {

            byte[] bb = dompanyCodec.encode(company);
        }
        System.out.print(String.format("Encode for 10000 times elapsed: %d\n", System.currentTimeMillis() - start));

        // 反序测试
        start = System.currentTimeMillis();
        loop = 10000;
        byte[] bytes = dompanyCodec.encode(company);
        while (loop-- > 0) {
            // 反序
            Company company = dompanyCodec.decode(bytes);
        }
        System.out.print(String.format("Decode for 10000 times elapsed: %d\n", System.currentTimeMillis() - start));
    }
}

**Comment by xiemalin** [comment]
性能问题已经修复 . 修复版本号为 1.11.6和2.2.7
