### ISSUE TITLE
INT32为什么默认不使用ZigZag编码呢?

### ISSUE THREAD

**Issue by iSenninha** [jhunters/jprotobuf#103]
```
@Protobuf
private int test
```
你好，如果**Protobuf**注解上没有写明使用**fieldType = FieldType.SINT32**的话，默认是变成了**INT_32**，而**INT_32**不会走**ZigZag**压缩，写一个绝对值很小的负数，也会编码成10byte长。
请教一下为什么**INT_32**默认不走**ZigZag**压缩

**Comment by xiemalin** [comment]
你是在pb的哪个版本测试的？我看了pb2.5的实现， sint32与int32在处理上，没有特别不同之处

**Comment by iSenninha** [comment]
jprotobuf2.07，依赖的是pb3.0.2

**ArrayEncoder** sint32编码:
```
    @Override
    public final void writeInt32(final int fieldNumber, final int value) throws IOException {
      writeTag(fieldNumber, WireFormat.WIRETYPE_VARINT);
      writeInt32NoTag(value);
    }
```
sint32是:
```
  /** Write a {@code sint32} field, including tag, to the stream. */
  public final void writeSInt32(final int fieldNumber, final int value) throws IOException {
    writeUInt32(fieldNumber, encodeZigZag32(value));
  }
```
这两种方法同时编码-1，int32成了10个字节，sint32是1个字节

**Comment by xiemalin** [comment]
pb 3.0引入 这个特性，后续会发版本升级

**Comment by jhunters** [comment]
从版本 1.11.7 and 2.2.8 开始支持@EnableZigZap 注解，针对 未指定类型情况下，针对int和long 使用 sint32和sint64类型
