### ISSUE TITLE
List<Enum>无法解析

### ISSUE THREAD

**Issue by chancy901030** [jhunters/jprotobuf#107]

**Comment by jhunters** [comment]
类型指定为枚举就可以了
@Protobuf(fieldType = FieldType.ENUM)
枚举对象先实现一下面接口吧
public enum EnumAttrPOJO implements EnumReadable {
普通枚举实现我再看一下问题

**Comment by chancy901030** [comment]
public enum TestEnum implements EnumReadable{
    A_TYPE(1),
    B_TYPE(2),
    C_TYPE(3),
    ;

    private final int value;
    TestEnum(int value){
        this.value = value;
    }

    public int toValue() { return this.value; }

    @Override
    public int value() {
        return value;
    }
}

public final static class TestSimple {
        @Protobuf(fieldType = FieldType.INT32, order = 1)
        public int intValue;

        @Protobuf(fieldType = FieldType.DOUBLE, order = 2)
        public double doubleValue;

        @Protobuf(fieldType = FieldType.BOOL, order = 3)
        public boolean boolValue;

        @Protobuf(fieldType = FieldType.STRING, order = 4)
        public String stringValue;

        @Protobuf(fieldType = FieldType.ENUM,order = 5)
        public TestEnum enumValue;
    }

public final static class TestComplex {
    @Protobuf(fieldType = FieldType.INT32, order = 1)
    public List<Integer> intArrayValue;

    @Protobuf(fieldType = FieldType.DOUBLE, order = 2)
    public List<Double> doubleArrayValue;

    @Protobuf(fieldType = FieldType.BOOL, order = 3)
    public List<Boolean> boolArrayValue;

    @Protobuf(fieldType = FieldType.STRING, order = 4)
    public List<String> stringArrayValue;

    @Protobuf(fieldType = FieldType.OBJECT, order = 5)
    public List<TestSimple> objArrayValue;

    @Protobuf(fieldType = FieldType.ENUM, order = 6)
    public List<TestEnum> enumArrayValue;

    @Protobuf(fieldType = FieldType.MAP,order = 7)
    public Map<Integer,TestSimple> mapValue;
}

我是这样用的，解析出来objArrayValue都没问题，enumArrayValue是个null，不过很感谢这么即时的回复，也很感谢做出这么优秀的项目，我在测试protostuff的时候发现嵌套对象有问题，偶然发现这个项目的，解决了我的燃眉之急，万分感谢

**Comment by jhunters** [comment]
测试了一下你的代码，我没发现你说的 enumArrayValue是个null的问题
        List<TestEnum> enumArrayValue = new ArrayList<TestEnum>();
        enumArrayValue.add(TestEnum.A_TYPE);
        enumArrayValue.add(TestEnum.B_TYPE);
        
        TestComplex pojo = new TestComplex();
        pojo.enumArrayValue = enumArrayValue;
        
        Codec<TestComplex> codec = ProtobufProxy.create(TestComplex.class);
        byte[] encode = codec.encode(pojo);
        System.out.println(Arrays.toString(encode));

**Comment by jhunters** [comment]
补充 List<Enum>无法解析 的解决办法， 在泛型中，不要使用Enum这个抽象类，因为pb序列化是不会传参数名和类型的，所以没办法识别到具体要转换成什么。 可以改成
List<TestEnum>具体的enum对象类就可以

**Comment by chancy901030** [comment]
哦，sorry，我是用protobuf encode，然后用jprotobuf解析的，我把完整的测试用例发给你吧，只有用jprotobuf解析protobuf序列化的有问题，其他的都没问题
[test.zip](https://github.com/jhunters/jprotobuf/files/2934136/test.zip)

**Comment by jhunters** [comment]
问题找到了， jprotobuf缺少对List<Enum>方式以packed方式的解析支持，后面会增加

**Comment by chancy901030** [comment]
OK，感谢

**Comment by jhunters** [comment]
2.2.9-SNAPSHOT 这个版本已经修正了该功能
