### ISSUE TITLE
自动推倒类型时 map<> 存在问题,可以手动指定类型解决

### ISSUE THREAD

**Issue by daonidedie** [jhunters/jprotobuf#108]
数据代码定义如下：

    @Protobuf(order = 9993)
    public Map<Integer, Double> ABC;

使用以上定义时会在运行时出现错误
需要: int,java.util.Map<K,V>,com.google.protobuf.WireFormat.FieldType,K,com.google.protobuf.WireFormat.FieldType,V
  找到: int,java.lang.Object,com.google.protobuf.WireFormat.FieldType,int,com.google.protobuf.WireFormat.FieldType,double
  原因: 无法推断类型变量 K,V
    (参数不匹配; java.lang.Object无法转换为java.util.Map<K,V>), RealTimeUpEntity$$JProtoBufClass.java:1283: 错误: 无法将类 com.baidu.bjf.remoting.protobuf.code.CodedConstant中的方法 writeToMap应用到给定类型;
CodedConstant.writeToMap(output,9993,f_9993,com.google.protobuf.WireFormat.FieldType.INT32,0,com.google.protobuf.WireFormat.FieldType.DOUBLE,0d);

解决方法：可以手动指定类型
       @Protobuf(order = 9993, fieldType = FieldType.MAP)
    public Map<Integer, Double> ABC;

**Comment by daonidedie** [comment]
补充一下，版本是2.2.8

**Comment by jhunters** [comment]
2.2.9-SNAPSHOT 版本已经修复该问题
