### ISSUE TITLE
注解@ProtobufClass不支持预编译 

### ISSUE THREAD

**Issue by jiashuntian** [jhunters/jprotobuf#111]

**Comment by jhunters** [comment]
升级你的 jprotobuf-precompile-plugin 版本到最新的就行

**Comment by jiashuntian** [comment]
<plugin>
                <groupId>com.baidu</groupId>
                <artifactId>jprotobuf-precompile-plugin</artifactId>
                <version>2.0.8</version>

已经是最新版本了


![image](https://user-images.githubusercontent.com/49695140/57902623-d2e58800-789c-11e9-94b4-ba0e486db38f.png)
预编译插件没有针对 ProtobufClass注解做检测

**Comment by jhunters** [comment]
新版本已经支持
 1.2.14 &  2.0.9
