### ISSUE TITLE
jprotobuf2.2.10版本中的 FileDescriptorProtoPOJO没有预编译出对应的 $$JProtoBufClass 

### ISSUE THREAD

**Issue by jiashuntian** [jhunters/jprotobuf#112]
![image](https://user-images.githubusercontent.com/49695140/57901286-ff96a100-7896-11e9-86b6-6367cdcb9fe8.png)

**Comment by jiashuntian** [comment]
为什么缺少FileDescriptorProtoPOJO对应的$$JProtoBufClass预编译class?

**Comment by jhunters** [comment]
这个问题我们跟进一下

**Comment by jiashuntian** [comment]
我手动生成FileDescriptorProtoPOJO$$JProtoBufClass 放进jar包中，不报错了，可以序列化，但是反序列化成java对象时 字段都空的。

**Comment by jhunters** [comment]
已经修复，fix version at 2.2.11

**Comment by jiashuntian** [comment]
![image](https://user-images.githubusercontent.com/49695140/57915651-d2acb300-78c3-11e9-84a8-6e5ca5a81a5f.png)
我更新了下2.2.11还是没有 FileDescriptorProtoPOJO对应的$$JProtoBufClass预编译class

**Comment by jhunters** [comment]
已经有了呀 http://repo1.maven.org/maven2/com/baidu/jprotobuf/2.1.11/ 这个maven下载下来的
![image](https://user-images.githubusercontent.com/6335563/57915983-89109800-78c4-11e9-89c8-aca4d5ddf6b6.png)

**Comment by jiashuntian** [comment]
https://maven.aliyun.com/repository/central/com/baidu/jprotobuf/2.2.11/jprotobuf-2.2.11.jar
我从阿里仓储上更新的，这边是有问题的缺少对应的预编译class

**Comment by jiashuntian** [comment]
谢谢

**Comment by jhunters** [comment]
还真是， 好奇怪，不知道阿里云从哪个拉的库，我的确分布过两次这个版本。 这样吧我再发布更新 一次版本号吧
