### ISSUE TITLE
@ProtobufClass注解，预编译时，当有Map属性，在没有添加@Protobuf(fieldType = FieldType.MAP)注解情况下 预编失败。

### ISSUE THREAD

**Issue by jiashuntian** [jhunters/jprotobuf#113]
![image](https://user-images.githubusercontent.com/49695140/57916860-5071be00-78c6-11e9-984d-0362f2289694.png)
![image](https://user-images.githubusercontent.com/49695140/57916891-654e5180-78c6-11e9-9191-c989d4b23797.png)

@ProtobufClass注解，预编译时，当有Map属性，在没有添加@Protobuf(fieldType = FieldType.MAP)注解情况下 预编失败。

**Comment by jhunters** [comment]
是编译插件有问题，下一个版本修复

**Comment by jhunters** [comment]
问题已经修复 使用  jprotobuf-precompile-plugin  2.0.10 版本
