### ISSUE TITLE
jprotobuf-2.2.13.jar FileDescriptorProtoPOJO 没有预编译出 FileDescriptorProtoPOJO$$JProtoBufClass

### ISSUE THREAD

**Issue by craneding** [jhunters/jprotobuf#117]
jprotobuf-2.2.13.jar 仓库地址：http://repo1.maven.org/maven2/com/baidu/jprotobuf/2.2.13/jprotobuf-2.2.13.jar
![DA196842-84E4-418A-802A-ECC2AC36505A](https://user-images.githubusercontent.com/6929198/61027064-c20e4a00-a3e7-11e9-9604-852bdf5defb1.png)

**Comment by 759434091** [comment]
换个版本。我也遇见过有版本漏掉。 或者在预编译插件加上这个包预编译试试？

**Comment by jhunters** [comment]
下一个版本会修复一下

**Comment by jhunters** [comment]
2.2.14版本已经修复
