### ISSUE TITLE
@Protobuf注解对repeated字段解析有问题

### ISSUE THREAD

**Issue by FancyJan** [jhunters/jprotobuf#129]
`public class EchoResponse {
@Protobuf(fieldType=FieldType.STRING, order=1, required=false)
    private java.util.List<String> message;
}
`
brpc Java client 连 brpc C++ server，
server返回的repeated字段不能被正确解析（在client这边看结果为空）
但是如果不用 @Protobuf注解，改用@ProtobufClass注解的话就不会有这个问题

参照组，grpc Java client 连 brpc C++ server，
server返回的repeated字段能被正确解析

**Comment by jhunters** [comment]
测试下来，没有发现该问题，请问使用的具体版本是？

**Comment by FancyJan** [comment]
1.2.15

**Comment by FancyJan** [comment]
我后来改用2.2.14就没有这个问题了
