### ISSUE TITLE
@Protobuf的order属性是否应该为必选？

### ISSUE THREAD

**Issue by amsz** [jhunters/jprotobuf#13]
在协议定义时，字段顺序通常是明确的，使用默认值时如果不小心在中间新加了一个字段，就会造成协议不兼容，是否可以考虑设置必选？

另外，是否可以考虑order不定义的话，忽略该字段？

**Comment by jhunters** [comment]
这个方案也是之前考虑到大家使用上的便捷考虑的，所以暂时不会进行方案调整，从推荐的使用方法上是建议大家使用时明确指定order的内容

**Comment by amsz** [comment]
一个对象中，如果某些字段定义了@Protobuf，还有些字段没有定义@Protobuf，没有定义@Protobuf的字段会被忽略，是这样吗？

**Comment by jhunters** [comment]
是的，只会针对@Protobuf注解定义字段有效

**Comment by amsz** [comment]
谢谢你的答复
