### ISSUE TITLE
pb3转换添加字段默认值？

### ISSUE THREAD

**Issue by FancyJan** [jhunters/jprotobuf#131]
jprotobuf 2.x 能不能支持生成的java文件的字段按照类型带默认值

**Comment by FancyJan** [comment]
> jprotobuf 2.x 能不能支持生成的java文件的字段按照类型带默认值

比如 proto里面 int a = 1；string b = 2；
在 生成的java文件里面
@Protobuf(fieldType=FieldType.INT32, order=1, required=false)
public String a = 0;
@Protobuf(fieldType=FieldType.STRING, order=2, required=false)
public String b = "";

**Comment by jhunters** [comment]
指  从proto文件，生成jprotobuf java 代码，带上默认值 ，是这个意思吗？

**Comment by FancyJan** [comment]
> 指 从proto文件，生成jprotobuf java 代码，带上默认值 ，是这个意思吗？

是的

**Comment by jhunters** [comment]
现在好像已经支持 ，使用方式如 string message = 1 [default = \"hello\"];
