### ISSUE TITLE
List<Integer> 类型支持

### ISSUE THREAD

**Issue by amsz** [jhunters/jprotobuf#14]
集合不支持没有构造函数的对象类型，例如List<Integer>，初始化时报错。

原生的protobuf是可以支持的：repeated int32 xxx = 1;

**Comment by jhunters** [comment]
List<Integer> 类型是完全支持了，具体使用可以详见 test代码中的 simplerepeat包下RequrieRepeatedNumberType2Test 这个类，他就针对List<Integer> 方式的使用测试

**Comment by amsz** [comment]
看到了，需要定义fieldType = FieldType.INT32，谢谢~
