### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.codehaus.plexus:plexus-utils:jar

### ISSUE THREAD

**Issue by Bing-ok** [jhunters/jprotobuf#140]
## Issue description
Hi, there are multiple versions of **_org.codehaus.plexus:plexus-utils_** in **_jprotobuf-master\jprotobuf-precompile-plugin_**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **_org.codehaus.plexus:plexus-utils:1.5.15_** can be loaded, **_org.codehaus.plexus:plexus-utils:1.0.4_**, **_org.codehaus.plexus:plexus-utils:1.4.1_** and **_org.codehaus.plexus:plexus-utils:1.4.2_** will be shadowed.

However, one method defined in shadowed version **_org.codehaus.plexus:plexus-utils:1.4.1_** is referenced by client project via **_org.apache.maven:maven-toolchain:1.0_**, but missing in the actually loaded version **_org.codehaus.plexus:plexus-utils:1.5.15_**.

For instance, the following missing method(defined in **_org.codehaus.plexus:plexus-utils:1.4.1_**) is actually referenced by **_jprotobuf-master\jprotobuf-precompile-plugin_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_jprotobuf-master\jprotobuf-precompile-plugin_**.

**_Missing method: org.codehaus.plexus.util.interpolation.RegexBasedInterpolator: java.lang.String interpolate(java.lang.String,java.lang.String)_** is invoked by **_jprotobuf-master\jprotobuf-precompile-plugin_** via the following path:
<pre><code>
paths------
&lt;com.baidu.jprotobuf.mojo.PreCompileMojo: void execute()&gt; jprotobuf-master\jprotobuf-precompile-plugin\target\classes
&lt;com.baidu.jprotobuf.mojo.PreCompileMojo: java.lang.ClassLoader getClassLoader()&gt; jprotobuf-master\jprotobuf-precompile-plugin\target\classes
&lt;com.baidu.jprotobuf.mojo.PreCompileMojo: void addRelevantPluginDependenciesToClasspath(java.util.List)&gt; jprotobuf-master\jprotobuf-precompile-plugin\target\classes
&lt;com.baidu.jprotobuf.mojo.PreCompileMojo: java.util.Set determineRelevantPluginDependencies()&gt; jprotobuf-master\jprotobuf-precompile-plugin\target\classes
&lt;com.baidu.jprotobuf.mojo.PreCompileMojo: java.util.Set resolveExecutableDependencies(org.apache.maven.artifact.Artifact)&gt; jprotobuf-master\jprotobuf-precompile-plugin\target\classes
&lt;org.apache.maven.project.DefaultMavenProjectBuilder: org.apache.maven.project.MavenProject buildFromRepository(org.apache.maven.artifact.Artifact,java.util.List,org.apache.maven.artifact.repository.ArtifactRepository)&gt; Repositories\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar
&lt;org.apache.maven.project.DefaultMavenProjectBuilder: org.apache.maven.project.MavenProject buildFromRepository(org.apache.maven.artifact.Artifact,java.util.List,org.apache.maven.artifact.repository.ArtifactRepository,boolean)&gt; Repositories\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar
&lt;org.apache.maven.project.DefaultMavenProjectBuilder: org.apache.maven.project.MavenProject buildInternal(java.lang.String,org.apache.maven.model.Model,org.apache.maven.artifact.repository.ArtifactRepository,java.util.List,java.io.File,org.apache.maven.profiles.ProfileManager,boolean)&gt; Repositories\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar
&lt;org.apache.maven.project.DefaultMavenProjectBuilder: org.apache.maven.project.MavenProject assembleLineage(org.apache.maven.model.Model,java.util.LinkedList,org.apache.maven.artifact.repository.ArtifactRepository,java.io.File,java.util.List,java.util.Set,org.apache.maven.profiles.ProfileManager,boolean)&gt; Repositories\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar
&lt;org.apache.maven.project.DefaultMavenProjectBuilder: void loadProjectExternalProfiles(org.apache.maven.profiles.ProfileManager,java.io.File)&gt; Repositories\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar
&lt;org.apache.maven.profiles.DefaultMavenProfilesBuilder: org.apache.maven.profiles.ProfilesRoot buildProfiles(java.io.File)&gt; Repositories\org\apache\maven\maven-profile\2.0.6\maven-profile-2.0.6.jar
&lt;org.codehaus.plexus.util.interpolation.RegexBasedInterpolator: java.lang.String interpolate(java.lang.String,java.lang.String)&gt;
</code></pre>

## Suggested fixing solutions
1. Upgrade dependency **_org.apache.maven:maven-toolchain_** from **_1.0_** to **_2.0.9_**. Because the newer version **_org.apache.maven:maven-toolchain:2.0.9_** does not invoke the above missing method, such upgrading can solve the problem.
2. Declare a direct dependency **_org.codehaus.plexus:plexus-utils:1.4.3_** in the pom file of **_jprotobuf-master\jprotobuf-precompile-plugin_**. Because version **_1.4.3_** includes the above missing method and is compatible with other versions of **_org.codehaus.plexus:plexus-utils_** in the project.
3. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library **_org.codehaus.plexus:plexus-utils_** to be **_1.4.3_** in jprotobuf-master\jprotobuf-precompile-plugin's pom file.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.baidu:jprotobuf-precompile-plugin:maven-plugin:1.4.0
[INFO] +- org.apache.maven:maven-toolchain:jar:1.0:compile
[INFO] |  +- org.apache.maven:maven-core:jar:2.0.6:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:2.0.6:compile
[INFO] |  |  |  +- (org.apache.maven:maven-model:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- org.apache.maven.wagon:wagon-file:jar:1.0-beta-2:runtime
[INFO] |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  +- org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6:compile
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- org.apache.maven.wagon:wagon-http-lightweight:jar:1.0-beta-2:runtime
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:1.0-beta-2:runtime
[INFO] |  |  |  |  +- jtidy:jtidy:jar:4aug2000r7-dev:runtime
[INFO] |  |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  |  +- xml-apis:xml-apis:jar:1.0.b2:runtime
[INFO] |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  +- org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[INFO] |  |  |  \- org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[INFO] |  |  +- org.apache.maven:maven-profile:jar:2.0.6:compile
[INFO] |  |  |  +- (org.apache.maven:maven-model:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- org.apache.maven:maven-model:jar:2.0.6:compile
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-artifact:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:compile - omitted for conflict with 1.0-beta-6)
[INFO] |  |  +- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-repository-metadata:jar:2.0.6:compile - omitted for conflict with 2.2.1)
[INFO] |  |  +- org.apache.maven:maven-error-diagnostics:jar:2.0.6:compile
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- org.apache.maven:maven-project:jar:2.0.6:compile
[INFO] |  |  |  +- (org.apache.maven:maven-settings:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.maven:maven-profile:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.maven:maven-model:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.maven:maven-artifact-manager:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[INFO] |  |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)
[INFO] |  |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  |  +- <b>(org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for duplicate)</b>
[INFO] |  |  |  +- (org.apache.maven:maven-artifact:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- commons-cli:commons-cli:jar:1.0:compile
[INFO] |  |  +- (org.apache.maven:maven-plugin-api:jar:2.0.6:compile - omitted for conflict with 2.2.1)
[INFO] |  |  +- org.apache.maven.wagon:wagon-ssh-external:jar:1.0-beta-2:runtime
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.0.4:runtime - omitted for conflict with 1.4.1)
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-ssh-common:jar:1.0-beta-2:runtime
[INFO] |  |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.0.4:runtime - omitted for conflict with 1.4.1)
[INFO] |  |  |  |  +- (org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:runtime - omitted for duplicate)
[INFO] |  |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  +- org.apache.maven:maven-plugin-descriptor:jar:2.0.6:compile
[INFO] |  |  |  +- (org.apache.maven:maven-plugin-api:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.maven:maven-artifact:jar:2.0.6:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO] |  |  +- org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[INFO] |  |  |  \- (classworlds:classworlds:jar:1.1-alpha-2:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-artifact-manager:jar:2.0.6:compile - omitted for conflict with 2.2.1)
[INFO] |  |  +- org.apache.maven:maven-monitor:jar:2.0.6:compile
[INFO] |  |  +- org.apache.maven.wagon:wagon-ssh:jar:1.0-beta-2:runtime
[INFO] |  |  |  +- com.jcraft:jsch:jar:0.1.27:runtime
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:runtime - omitted for duplicate)
[INFO] |  |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.0.4:runtime - omitted for conflict with 1.4.1)
[INFO] |  |  |  +- (org.apache.maven.wagon:wagon-ssh-common:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  |  \- (org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:runtime - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.4.1:compile - omitted for conflict with 1.5.15)
[INFO] |  |  \- classworlds:classworlds:jar:1.1:compile
[INFO] |  \- (org.apache.maven:maven-artifact:jar:2.0.6:compile - omitted for conflict with 2.2.1)
[INFO] +- org.apache.maven:maven-artifact:jar:2.2.1:compile
[INFO] |  \- <b>org.codehaus.plexus:plexus-utils:jar:1.5.15:compile</b> 
[INFO] +- org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[INFO] |  +- org.apache.maven:maven-repository-metadata:jar:2.2.1:compile
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for duplicate)
[INFO] |  +- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for duplicate)
[INFO] |  +- (org.apache.maven:maven-artifact:jar:2.2.1:compile - omitted for duplicate)
[INFO] |  +- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[INFO] |  |  +- junit:junit:jar:3.8.1:compile
[INFO] |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.0.4:compile - omitted for conflict with 1.5.15)
[INFO] |  |  \- (classworlds:classworlds:jar:1.1-alpha-2:compile - omitted for conflict with 1.1)
[INFO] |  +- org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-6:compile
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:1.4.2:compile - omitted for conflict with 1.5.15)
[INFO] |  \- backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[INFO] +- org.apache.maven:maven-plugin-api:jar:2.2.1:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.3:provided
[INFO] |  \- (org.apache.maven:maven-artifact:jar:3.0:provided - omitted for conflict with 2.2.1)
[INFO] +- org.jodd:jodd-core:jar:3.5.2:compile
[INFO] +- com.baidu:jprotobuf:jar:1.13.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  +- com.squareup:protoparser:jar:3.1.5:compile
[INFO] |  +- org.javassist:javassist:jar:3.26.0-GA:compile
[INFO] |  +- (commons-io:commons-io:jar:2.6:compile - omitted for conflict with 1.4)
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] \- commons-io:commons-io:jar:1.4:compile
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @jhunters

**Comment by Bing-ok** [comment]
@jhunters Could you please help me review this issue? Thank you very much.

**Comment by jhunters** [comment]
jprotobuf-precompile-plugin 1.4.2 supports   org.apache.maven:maven-toolchain from 1.0 to 2.0.9 now.

**Comment by jhunters** [comment]
many thanks for ur suggestions

**Comment by Bing-ok** [comment]
Thanks for your support!
