### ISSUE TITLE
Jprotobuf增加对枚举类型的支持

### ISSUE THREAD

**Issue by xiemalin** [jhunters/jprotobuf#15]
1. @Protobuf 注释支持枚举类型的支持
2. ProtobufIDLGenerator 支持枚举类型的idl生成
3. ProtobufIDLProxy支持包含枚举类型的idl动态代理支持，但目前不支持包含内部类与内部枚举类型方式

**Comment by jhunters** [comment]
已完成 版本 1.5.0
