### ISSUE TITLE
预编译插件在 某引用类型为repeat模式时(包括Collection,Map) 生成的proto文件中该引用类型存在重复定义的问题

### ISSUE THREAD

**Issue by peterveron** [jhunters/jprotobuf#151]
版本2.4.5
![image](https://user-images.githubusercontent.com/20771943/103653783-fb555500-4f9f-11eb-938a-865423a8bb51.png)
上面这种情形下生成的proto文件中 RespBuilding只有一个定义, 不会出问题
但是下面这种情形
![image](https://user-images.githubusercontent.com/20771943/103653931-2f307a80-4fa0-11eb-859e-83e263482a83.png)
生成的proto文件中会存在重复的RespBuilding定义, 导致无法通过protoc编译

**Comment by peterveron** [comment]
花了点时间测试跟检查代码, 都使用List的情形下不会出问题, 所以排除List型, 但是 一旦有Map 就会出问题
下面是跟踪代码发现的问题, 请确认一下
![image](https://user-images.githubusercontent.com/20771943/103726361-bf5bd780-5013-11eb-833c-dd04286798f0.png)

**Comment by jhunters** [comment]
代码中使用的是set结构，按理不会有重复的情况出现。测试了一下，也没有复现你那个问题，能否把生成的proto内容也发一下出来？

**Comment by peterveron** [comment]
[JProtobufTest_java.txt](https://github.com/jhunters/jprotobuf/files/5901729/JProtobufTest_java.txt)
[JProtobufTest_proto.txt](https://github.com/jhunters/jprotobuf/files/5901730/JProtobufTest_proto.txt)

**Comment by jhunters** [comment]
已在2.2.5版本修复
