### ISSUE TITLE
Java14 环境下无法正常使用

### ISSUE THREAD

**Issue by FULaBUla** [jhunters/jprotobuf#153]
# 开发环境

- idea 2020.3.2
- gradle 6.6.1
- java 14 oracle
- 项目语言级别 11

# 异常
运行时提示
`JProtoBufClass, diagnostics: [错误: 不再支持源选项 6。请使用 7 或更高版本。, 错误: 不再支持目标选项 6。请使用 7 或更高版本。]`
出现问题的地方
`Codec<Test> studentClassCodec = ProtobufProxy.create(Test.class);`

**Comment by jhunters** [comment]
2.4.7 版本已修复该问题
