### ISSUE TITLE
增加对jprotobuf动态生成的类文件的生成

### ISSUE THREAD

**Issue by Baidu-etech** [jhunters/jprotobuf#17]
该功能可以支持把jprotobuf动态生成的中间代码的类文件输出到指定目录，以方便后续只有jre环境使用jprotobuf的可行性。

使用示例：Codec<AddressBookProtosPOJO> codec = ProtobufProxy.create(AddressBookProtosPOJO.class, false, new File("D:/"));

会在d盘根目录下生成中间的类文件对象。下次只需要把这个类文件对象加入到classpath中，就不会再执行动态编译过程了

**Comment by xiemalin** [comment]
功能已完成，参见版本 1.6.3
