### ISSUE TITLE
List<Integer>类型不支持

### ISSUE THREAD

**Issue by xbase** [jhunters/jprotobuf#18]
定义如下：
@Protobuf
private List\<Integer\> intList;

报错如下：
Class must has default constructor method with no parameters.

原始类型的数组或者list不支持？

**Comment by xiemalin** [comment]
你这个错误应该pojo对象必须要提供默认构造函数

**Comment by xbase** [comment]
恩 原始类型，比如：Integer 是没有默认构造函数，
@Protobuf
private List\<Integer\> intList;
这样的字段，应该怎么定义呢？

**Comment by xiemalin** [comment]
你这种情况，指定fieldType即可，如下：
    @Protobuf(fieldType = FieldType.INT32, order = 1, required = false)
    public List<Integer> list1;

**Comment by xbase** [comment]
定义字段如下：
@Protobuf(fieldType = FieldType.INT32, order = 4, required = false)
private List\<Integer\> list;
生成的proto文件内容如下：
optional int32 list=4;

以上只列出了出错的字段。
可以加您的QQ吗，关于Jprotobuf，还有一些问题想要咨询您。

**Comment by xiemalin** [comment]
你留一个QQ号给我吧

**Comment by xbase** [comment]
357254457 谢谢您啊
