### ISSUE TITLE
ProtobufProxy.create 在高并发的情况下会Block线程

### ISSUE THREAD

**Issue by Dr-Shiki** [jhunters/jprotobuf#195]
看起来在单机高QPS的情况下 调用ProtobufProxy.create (xxx.class)的情况下 会有大量线程block在其中的JDKCompiler.doCompile方法。有什么办法可以优化一下么

**Comment by jhunters** [comment]
doCompile 的性能是会比较慢，虽然加了缓存。 你可以考虑用 预编译的方式，在打包时把编译工作先处理了

**Comment by Imgaojp** [comment]
我们的做法是在启动后，应用正式接入流量前预热，在请求来之前先ProtobufProxy.create (xxx.class)

**Comment by jhunters** [comment]
也可以用 预编译的方式，预编译插件 配置 https:github.com/jhunters/jprotobuf/blob/master/Document.md
