### ISSUE TITLE
jprotobuf嵌套对象，多文件导出，嵌套对象定义重复

### ISSUE THREAD

**Issue by dogheadpig** [jhunters/jprotobuf#198]
![image](https://github.com/jhunters/jprotobuf/assets/134589289/853eed49-126f-4fed-8e9e-627d3d6f727e)
![image](https://github.com/jhunters/jprotobuf/assets/134589289/f04eb20e-a1cf-4f1a-a5ac-877be291c8c9)
![image](https://github.com/jhunters/jprotobuf/assets/134589289/30a0621b-32c3-40f4-a79c-858fc12eccd0)
![image](https://github.com/jhunters/jprotobuf/assets/134589289/7de20b33-4a03-42d9-9aa8-d8cc5135cb1d)
![image](https://github.com/jhunters/jprotobuf/assets/134589289/16b7395a-7e52-4eaf-ac6b-49a04ff5de23)
没有对应 proto文件的import写法

**Comment by jhunters** [comment]
把导出使用的方式发出来一下

**Comment by jhunters** [comment]
可以升级插件版本，支持去重的功能。
jprotobuf-precompile-plugin-2.2.9  jprotobuf-precompile-plugin-1.4.5

**Comment by LucaLq** [comment]
> 可以升级插件版本，支持去重的功能。 jprotobuf-precompile-plugin-2.2.9 jprotobuf-precompile-plugin-1.4.5

你好，你说的去重是这个配置么`<cacheBuildResult>true</cacheBuildResult>`，我测试了下还是会重复生成。
这是三个pojo类
```
@ProtobufClass
public class A {
    public C c;
}

@ProtobufClass
public class B {
    public C c;
}

@ProtobufClass
public class C {
    public String s;
}
```
生成的A.proto如下
```
syntax="proto3";
//
message A {  
 C c=1;
}
//
message C { 
 string s=1;
}
```
生成的B.proto如下
```
syntax="proto3";
//
message B {  
 C c=1;
}
//
message C { 
 string s=1;
}
```
生成的C.proto如下
```
syntax="proto3";
//
message C { 
 string s=1;
}
```
---
希望生成的A.proto和B.proto是如下的格式，请问有办法实现吗
```
syntax="proto3";]
import "C.proto"
//
message A {  
 C c=1;
}
```
