### ISSUE TITLE
List<String>这种可以支持吗？

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#20]
如题，这种应该对应那种fieldType？

**Comment by jhunters** [comment]
支持， fieldType对应的是STRING

**Comment by beykery** [comment]
不对啊，我试了下
public class Test
{
  @Protobuf(fieldType = FieldType.INT32, order = 1, required = false)
  private List<String> list;
}
使用IDLGen.getIDL(Test.class);生成的描述文件不对:
message Test{  
optional string list=1; // 站位
}
应该是repeated啊。。。
