### ISSUE TITLE
IDLGen.getIDL的问题

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#21]
public class Test
 {
 @Protobuf(fieldType = FieldType.INT32, order = 1, required = false)
 private List list;
 }

使用IDLGen.getIDL(Test.class);生成的描述文件不对:

message Test{
 optional string list=1; 
 }
应该是repeated啊。。。

**Comment by jhunters** [comment]
你的List需要指定泛型才可以。 同时你使用的版本是否最新的？
@Protobuf(fieldType = FieldType.INT32, order = 1, required = false)
public List&lt;Integer&gt; list1;

**Comment by beykery** [comment]
不是的
我是说IDLGen.getIDL(Test.class)的返回，生成的不应该是message Test{
optional string list=1; 
}

而应该是：
message Test{
repeated string list=1; 
}

**Comment by beykery** [comment]
public class Test
{
  @Protobuf(fieldType = FieldType.STRING, order = 1, required = false)
  private List<String> l;
}

IDLGen.getIDL(Test.class)以后：

message Test {  
optional string l=1;
}
应该是：
message Test{
repeated string l=1; 
}吧？

**Comment by jhunters** [comment]
这个在 1.7.0 版本已经修复了，请使用该 版本

**Comment by xiemalin** [comment]
该问题的确存在， 将在 1.7.1版本修复，谢谢！

**Comment by xiemalin** [comment]
Fixed  at  1.7.1
