### ISSUE TITLE
是否允许不包含任何 @Protobuf注解的对象存在？

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#22]
public class Empty
{
}

这样一个类是否应该也是合法的？protobuf是允许这样的对象的
不过使用jprotobuf的IDLGen.getIDL(Empty.class)会抛出异常

**Comment by xiemalin** [comment]
这个强制要求的，因为上面的使用根本没有场景和意义

**Comment by beykery** [comment]
有啊
有时候我们只是想标记一个类型而已，空属性的，就能明确业务的意义。

**Comment by xiemalin** [comment]
这种情况完全可以用枚举表示，用一个空对象类型来表示，不是很奇怪？

**Comment by beykery** [comment]
嗯我是觉得这也是一个选择
还有就是protobuf是允许存在，那么jprotobuf是否也应该跟它保持一致。

**Comment by xiemalin** [comment]
Fixed  at  1.7.1
