### ISSUE TITLE
ProtobufIDLGenerator是否可以提供一个重载的getIDL(Class<?> cls)方法？

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#23]
ProtobufIDLGenerator目前只有getIDL(Class<?> cls)一个public方法，我们还是需要一个这样的方法：
getIDL(Class<?> cls,Set<Class<?>> cachedTypes,Set<Class<?>> cachedEnumTypes)  因为有这个方法的话，就可以避免重复生成同一个类的idl；比如A类引用了B类，C类也引用了B类，当生成A的idl后其实已经生成了B的idl，再调用getIDL(Class<?> cls)传入C的时候，又一次生成B，
所以把两个cache作为参数传入还是有意义的。我目前是在我们的项目里修改这个ProtobufIDLGenerator并提供这个getIDL(Class<?> cls,Set<Class<?>> cachedTypes,Set<Class<?>> cachedEnumTypes) 方法的。

**Comment by xiemalin** [comment]
大概你们那边的需求是需要getIDL返回的生成message列表，以实现去重，是吧

**Comment by xiemalin** [comment]
feature will add at 1.7.2

**Comment by beykery** [comment]
是的，就是message去重。

**Comment by jhunters** [comment]
fixed at 1.7.3

    /**
     * get IDL content from class.
     * 
     * @param cls target class to parse for IDL message.
     * @param cachedTypes if type already in set will not generate IDL. if a new type found will add to set
     * @param cachedEnumTypes if enum already in set will not generate IDL. if a new enum found will add to set
     * @return protobuf IDL content in string
     * @see Protobuf
     */
    public static String getIDL(final Class<?> cls, final Set<Class<?>> cachedTypes, 
            final Set<Class<?>> cachedEnumTypes) {
