### ISSUE TITLE
使用primitive类型属性且没有指定getter方法时，会导致编译失败

### ISSUE THREAD

**Issue by xiemalin** [jhunters/jprotobuf#24]
演示代码如下：
```java
public class TestError {
      private int age;
}
```

**Comment by xiemalin** [comment]
java.lang.IllegalStateException: Compilation failed. class: com.baidu.bjf.remoting.protobuf.simpletypes.AllTypesPrimitivePojoClass$$JProtoBufClass, diagnostics: [AllTypesPrimitivePojoClass$$JProtoBufClass.java:12: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:13: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:14: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:19: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:20: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:21: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:26: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:27: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:28: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:33: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:34: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:35: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:40: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:41: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:42: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:47: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:48: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:49: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:54: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:55: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:56: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:61: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:62: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:63: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:68: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:69: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:70: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:75: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:76: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:77: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:82: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:83: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:84: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:89: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:90: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:91: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:96: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:97: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:98: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:220: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:221: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:222: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:227: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:228: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:229: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:234: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:235: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:236: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:241: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:242: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:243: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:248: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:249: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:250: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:255: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:256: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:257: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:262: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:263: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:264: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:269: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:270: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:271: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:276: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:277: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:278: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:283: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:284: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:285: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:290: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:291: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:292: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:297: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:298: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:299: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:304: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:305: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:306: 不可转换的类型
找到： java.lang.Object
需要： boolean, AllTypesPrimitivePojoClass$$JProtoBufClass.java:335: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:336: 不可转换的类型
找到： java.lang.Object
需要： double, AllTypesPrimitivePojoClass$$JProtoBufClass.java:338: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:339: 不可转换的类型
找到： java.lang.Object
需要： float, AllTypesPrimitivePojoClass$$JProtoBufClass.java:341: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:342: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:344: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:345: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:347: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:348: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:350: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:351: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:353: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:354: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:356: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:357: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:359: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:360: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:362: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:363: 不可转换的类型
找到： java.lang.Object
需要： long, AllTypesPrimitivePojoClass$$JProtoBufClass.java:365: 不可转换的类型
找到： java.lang.Object
需要： int, AllTypesPrimitivePojoClass$$JProtoBufClass.java:366: 不可转换的类型
找到： java.lang.Object
需要： int]
	at com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler.doCompile(JdkCompiler.java:117)
	at com.baidu.bjf.remoting.protobuf.utils.compiler.AbstractCompiler.compile(AbstractCompiler.java:67)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:204)
	at com.baidu.bjf.remoting.protobuf.ProtobufProxy.create(ProtobufProxy.java:105)
	at com.baidu.bjf.remoting.protobuf.simpletypes.AllTypesTest.testRequiredMutliTypeDecode(AllTypesTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by jhunters** [comment]
fixed at 1.7.3
