### ISSUE TITLE
怎么支持类似List<String> List<Integer> 的类型？

### ISSUE THREAD

**Issue by maoxianfly** [jhunters/jprotobuf#25]
怎么支持类似List<String> List<Integer> 的类型字段？

**Comment by jhunters** [comment]
示例代码如下：

    @Protobuf(fieldType = FieldType.STRING, order = 3, required = false)
    public List<String> list3;

    @Protobuf(fieldType = FieldType.INT32, order = 1, required = false)
    public List<Integer> list1;
