### ISSUE TITLE
由.proto 生成注解的POJO类

### ISSUE THREAD

**Issue by vontio** [jhunters/jprotobuf#27]
一般通信协议前后端使用的proto文件,服务器能直接通过proto生成带注解的POJO吗

**Comment by jhunters** [comment]
该功能只开放给内部，你那边具体的需求是？ 目前jprotobuf可支持直接从.proto文件生成代理对象
 ProtobufIDLProxy  可当作类似map对象的操作

**Comment by vontio** [comment]
服务器端自己使用存库的 可以用POJO->proto.
通信部分是前后端已经协商定义的proto文件,需要从proto->POJO.

找到这个库最原始的需求是因为原生的protobuf各种Builder转换太麻烦.
而jprotobuf可以直接从POJO encode  这个就是原始的需求.

**Comment by jhunters** [comment]
需要从proto->POJO. 可以开放出来。

**Comment by jhunters** [comment]
将在 1.7.4版本添加，请关注版本发布信息，谢谢！

**Comment by vontio** [comment]
谢谢! 有计划什么时候推出1.7.4吗
另外问一下 jprotobuf encode decode 的性能如何

**Comment by jhunters** [comment]
预计 本周日发布。

jprotobuf 主要性能消耗在 扫描类上注解，动态生成代码编译的过程。
在执行序列化与反序列化的过程中，几乎与protobuf生成的代码效率等同。

**Comment by vontio** [comment]
好的好的,期待啊

**Comment by jhunters** [comment]
1.7.4 is out now
added features:
ProtobufIDLProxy增加从proto描述文件生成带注解的java POJO对象的功能 详见readme说明
