### ISSUE TITLE
proto文件依赖另一个proto文件，生成POJO的时候会报错

### ISSUE THREAD

**Issue by xbase** [jhunters/jprotobuf#28]
使用1.7.4 Jprotobuf
测试新功能 通过 .proto文件生成POJO类
发现如果 proto文件依赖另一个proto文件，生成带注解的POJO类时 就会报错
例如：
package com.base.research;

option java_package = "com.base.research.protobufMsg.test";
option java_outer_classname = "AddressBookProto";

import "person.proto";

message AddressBook {
  repeated Person person = 1;
}

是不支持吗？

**Comment by jhunters** [comment]
该问题已经与 1.7.5版本进行修复。
使用的方法如下：
ProtobufIDLProxy.generateSource(File file, File sourceOutputPath) throws IOException

**Comment by xbase** [comment]
使用1.7.5版本，依旧报错，报错信息和之前一样。

**Comment by sunxuejian** [comment]
我也遇到了此类问题。
version:2.2.9
![image](https://user-images.githubusercontent.com/21055134/55314844-951fd200-549d-11e9-8dc4-0e00fa2649f8.png)
error:
![image](https://user-images.githubusercontent.com/21055134/55314895-b41e6400-549d-11e9-94f6-3bc6a9d0efd4.png)

**Comment by jhunters** [comment]
需要把 import public "English"; 修改成  import "English";
