### ISSUE TITLE
1.7.5，proto文件依赖另一个proto文件，生成POJO的时候会报错

### ISSUE THREAD

**Issue by xbase** [jhunters/jprotobuf#29]
jprotobuf项目的测试用例中，好像仅仅 import "si_product_biz_ref.proto"，并没有实际使用 依赖的proto文件中定义的message。

**Comment by jhunters** [comment]
能否把具体的错误与相关的proto配置文件发出来，我测试一下。 上次版本主要修改的import功能无法启效的问题。   而且 只支持 public static void generateSource(File file, File sourceOutputPath) throws IOException { 这个方法

**Comment by xbase** [comment]
addressbook.proto文件：
package com.base.research;
option java_package = "com.base.research.protobufMsg.test";
option java_outer_classname = "AddressBookProto";

import "person.proto";

message AddressBook {
  repeated Person person = 1;
}

person.proto文件：
package com.base.research;
option java_package = "com.base.research.protobufMsg.test";
option java_outer_classname = "PersonProto";

message Person {
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;
}

测试代码：
File file = new File(PTMain.class.getResource("./proto/addressbook.proto").getFile());
ProtobufIDLProxy.generateSource(file, new File(generatorPath));

**Comment by jhunters** [comment]
Will  fix at 1.7.6

**Comment by jhunters** [comment]
已经修复 。修复版本 1.7.8
