### ISSUE TITLE
不支持Map吗

### ISSUE THREAD

**Issue by vontio** [jhunters/jprotobuf#30]
不支持Map吗

**Comment by vontio** [comment]
https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-2
protobuf v3 支持map了.

**Comment by jhunters** [comment]
Map 的支持对于开发人员来讲，是非常有吸引力的地方。 目前V3该版本还处于内测试阶段， 会考虑等beta发布后，加入对protobuf v3的支持

**Comment by vontio** [comment]
功能可以先加入,让用户选择是否使用Map吧.

**Comment by jhunters** [comment]
会单独以分支版本的方式进行支持

**Comment by xiemalin** [comment]
2.0.1-SNAPSHOT 已经放出，支持map结构

https://github.com/jhunters/jprotobuf/tree/master/v3

**Comment by vontio** [comment]
Cool
