### ISSUE TITLE
proto生成jprotobuf Source代码：自循环引用无法生成代码

### ISSUE THREAD

**Issue by jhunters** [jhunters/jprotobuf#32]
现在有个proto文件用
ProtobufIDLProxy.generateSource(fis, new File(source));
方法无法生成pojo文件 请问是不支持还是格式不对？
用原生的是可以生成的

package pkg;

option java_package = "org.nutz.plugins.protobuf.pojo";
option java_outer_classname = "JJFlyProtocol";
message MixedDataTypeTable
{
	message BoolKVP
	{
		required string Key = 1;
		required bool Value = 2;
	}

	message BoolArrayKVP
	{
		required string Key = 1;
		repeated bool Values = 2;
	}

	message IntKVP
	{
		required string Key = 1;
		required sint64 Value = 2;
	}

	message IntArrayKVP
	{
		required string Key = 1;
		repeated sint64 Values = 2;
	}

	message FloatKVP
	{
		required string Key = 1;
		required float Value = 2;
	}

	message FloatArrayKVP
	{
		required string Key = 1;
		repeated float Values = 2;
	}

	message StringKVP
	{
		required string Key = 1;
		required string Value = 2;
	}

	message StringArrayKVP
	{
		required string Key = 1;
		repeated string Values = 2;
	}

	message MixedDataTypeTableKVP
	{
		required string Key = 1;
		required MixedDataTypeTable Value = 2;
	}

	message MixedDataTypeTableArrayKVP
	{
		required string Key = 1;
		repeated MixedDataTypeTable Values = 2;
	}

	repeated BoolKVP BoolKVPs = 1;
	repeated BoolArrayKVP BoolArrayKVPs = 2;
	repeated IntKVP IntKVPs = 3;
	repeated IntArrayKVP IntArrayKVPs = 4;
	repeated FloatKVP FloatKVPs = 5;
	repeated FloatArrayKVP FloatArrayKVPs = 6;
	repeated StringKVP StringKVPs = 7;
	repeated StringArrayKVP StringArrayKVPs = 8;
	repeated MixedDataTypeTableKVP MixedDataTypeTableKVPs = 9;
	repeated MixedDataTypeTableArrayKVP MixedDataTypeTableArrayKVPs = 10;
}

message JJFlyMessageItem
{
	required sint64 ID = 1;								 
	required MixedDataTypeTable Value = 2;				 
}

message JJFlyMessageRequestBody
{
	required sint64 BaseProtocolVersion = 1;				
	optional string AppID = 2;							 
	optional sint64 ProtocolVersion = 3;					 
	optional sint64 AppVersion = 4;						 
	optional sint64 ResVersion = 5;						 
	optional string Language = 6 [default = "en-US"];	 
	optional string DistributionChannel = 7;			 
	optional string SessionID = 8;						 
	optional sint64 SessionSerialNumber = 9;				 
	repeated JJFlyMessageItem JJFlyMessageItems = 15;	 
}

message JJFlyMessageResponseBody
{
	optional string SessionID = 1;						 
	optional sint64 SessionSerialNumber = 2;				 
	repeated JJFlyMessageItem JJFlyMessageItems = 15;	 
}

**Comment by jhunters** [comment]
TODO:  to fix at  1.7.0

**Comment by xiemalin** [comment]
Fixed at  1.7.9.
