### ISSUE TITLE
默认值会被encode

### ISSUE THREAD

**Issue by vontio** [jhunters/jprotobuf#36]
一个类有10个字段,如果只使用了其中1个字段,其他9个字段 "应该" 不会encode.

**Comment by xiemalin** [comment]
是的， 不用的字段，不加@Protobuf注解就会忽略

**Comment by vontio** [comment]
10个optional字段,如果没有赋值,encode出来的bytes应该是空的.
对比了一下google实现的protobuf,如果直接newBuilder.Build  encode出来是一个空bytes.

**Comment by xiemalin** [comment]
google实现的protobuf 判空是需要 调用 hasxxx的方式，而不是根据值来判断的

**Comment by vontio** [comment]
是的,如果没有赋值,hasXXX == false  就不会encode
