### ISSUE TITLE
ProtobufIDLGenerator的bug

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#37]
举个例子：
public class Test
{
  @Protobuf
  private List<String> bps;
   
public List<String> getBps()
  {
    return bps;
  }
  public void setBps(List<String> bps)
  {
    this.bps = bps;
  }
}

这个类，调用ProtobufIDLGenerator的getIDL(Test.class,new HashSet<Class<?>>(),new HashSet<Class<?>>(),true);
生成如下idl：

message Test
{ 
repeated String bps=1;
}
message String {  
}

应该生成这样的吧：
message Test
{ 
repeated string bps=1;
}

**Comment by xiemalin** [comment]
是否是使用的版本问题，请使用的最新的版本进行测试

**Comment by beykery** [comment]
是最新的版本了：1.7.9

**Comment by xiemalin** [comment]
针对List类型，要求指定类型即可
@Protobuf(fieldType = FieldType.STRING, order = 1, required = false)
private List bps;

**Comment by beykery** [comment]
明白了。可以的。
