### ISSUE TITLE
增加maven预编译插件，提升jprotobuf启动性能

### ISSUE THREAD

**Issue by xiemalin** [jhunters/jprotobuf#39]
由于jprotobuf采用动态编译的技术，所以启动过程中会进行预编译，影响启动时间，maven编译插件实现把动态编译工作提前到编译发布阶段，提升启动性能

**Comment by xiemalin** [comment]
pom配置说明

			<plugin>
				<groupId>com.baidu</groupId>
				<artifactId>jprotobuf-precompile-plugin</artifactId>
				<version>1.2.0</version>
				<configuration>
					<skipErrorNoDescriptorsFound>true</skipErrorNoDescriptorsFound>
					<filterClassPackage>com.baidu</filterClassPackage>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>precompile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

运行命令：  maven clean package

**Comment by xiemalin** [comment]
使用方法参见:https://github.com/jhunters/jprotobuf
使用注意事项如下：
jprotobuf-precompile-plugin 支持maven编译时同时进行jprotobuf对象的预编译操作. 注：plugin版本建议使用>=1.2.0， jprotobuf 支持版本>=1.9.4

**Comment by p0mp0k0** [comment]
没有使用maven的项目如何解决这个问题呢？

**Comment by p0mp0k0** [comment]
没有使用maven的项目如何解决这个问题呢？
