### ISSUE TITLE
jprotobuf map支持问题

### ISSUE THREAD

**Issue by dempeZheng** [jhunters/jprotobuf#41]
<dependency>
  <groupId>com.baidu</groupId>
  <artifactId>jprotobuf</artifactId>
  <version>2.0.1-SNAPSHOT</version>
</dependency>
这个支持map的版本的jar哪个maven仓库有？

**Comment by xiemalin** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/baidu/jprotobuf/2.0.1-SNAPSHOT/

**Comment by dempeZheng** [comment]
thx
