### ISSUE TITLE
序列化List<String>的时候报错，求解

### ISSUE THREAD

**Issue by zhangweixin** [jhunters/jprotobuf#44]
![image](https://cloud.githubusercontent.com/assets/8088377/14815523/6c800122-0bde-11e6-9054-f68581337b7e.png)
请问为什么基本类型就报错了

**Comment by jhunters** [comment]
如果是List<String> 注释上需要写明 @Protobuf(fieldType=FieldType.STRING)

**Comment by lwlzpn84** [comment]
是不是有字段漏加 @Protobuf(fieldType=FieldType.STRING)

**Comment by zhangweixin** [comment]
确实是忘了加@Protobuf(fieldType=FieldType.STRING)

**Comment by gddghs** [comment]
![image](https://user-images.githubusercontent.com/19387347/61193500-3f8ad080-a6ee-11e9-81ee-bde32b7a0833.png)
我这边有加FieldType，但还是有这个报错呢，请问是什么原因呀？List<Integer>也是一样
