### ISSUE TITLE
什么时候会正式发布2.X版本

### ISSUE THREAD

**Issue by lwlzpn84** [jhunters/jprotobuf#45]
什么时候会正式发布2.X版本

**Comment by jhunters** [comment]
时间未定，主要是由于google protobuf 3.0的正式版本还没有发布，估计中间还会有修改。如果想使用的话，是可以直接使用的，主要看大家对 google protobuf 3.0的beta版本方式使用是否放心

**Comment by lwlzpn84** [comment]
google protobuf 2.6.1 应该已经支持了map类型的序列化，但是jprotobuf1.9.8好像还不支持map类型

**Comment by yourwafer** [comment]
any，map是protobuf3.x的东西，现在都到beta版本，应该快有release版本了

**Comment by lwlzpn84** [comment]
现在jprotobuf2.X的snapshot版本，没有放到maven的核心仓库，现在用起来还不是很方便，我现在是手动下载下来，更改snapshot的名称，然后本地环境在测试

**Comment by jhunters** [comment]
现在还在官方仓库的snapshot目录下

**Comment by lwlzpn84** [comment]
可能我们公司的maven仓库，没有配置连接你们这个核心仓库，2.0.1-SNAPSHOT无法下载下来，可以用源码自己编译打包吗？

**Comment by jhunters** [comment]
那你们可以暂且由源码打包来使用，等正式版发布后，我会再通知到你

**Comment by lwlzpn84** [comment]
thank you

**Comment by jhunters** [comment]
Latest release version 2.0.5
