### ISSUE TITLE
 不兼容的类型: java.util.List无法转换为java.util.ArrayList<

### ISSUE THREAD

**Issue by maoxianfly** [jhunters/jprotobuf#47]
--------------------------generate protobuf proxy code end--------------------------
Exception in thread "main" java.lang.IllegalStateException: Compilation failed. class: com.flhx.gate.player.bean.PlayerBaseInfo$$JProtoBufClass, diagnostics: [PlayerBaseInfo$$JProtoBufClass.java:101: 错误: 不兼容的类型: java.util.List无法转换为java.util.ArrayList<com.flhx.gate.player.bean.Building>
ret.setBuildings(__list);
                 ^, PlayerBaseInfo$$JProtoBufClass.java:114: 错误: 不兼容的类型: java.util.List无法转换为java.util.ArrayList<com.flhx.gate.player.bean.Resource>
ret.setResources(__list);
                 ^, PlayerBaseInfo$$JProtoBufClass.java:127: 错误: 不兼容的类型: java.util.List无法转换为java.util.ArrayList<com.flhx.gate.player.bean.Item>
ret.setItems(__list);

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by jhunters** [comment]
请把具体使用的代码贴出来吧

**Comment by maoxianfly** [comment]
public class TestBean {
    
     @Protobuf
    private ArrayList<Resource> resources;

  public ArrayList<Resource> getResources() {
        return resources;
    }

    public void setResources(ArrayList<Resource> resources) {
        this.resources = resources;
    }
}

======

ProtobufProxy.create(TestBean.class, false, new File(filedir));

**Comment by jhunters** [comment]
的确是转换的问题，你可以先这么修改来使用, 把ArrayList都改成List

public class TestBean {

 @Protobuf
private List<Resource> resources;
public List<Resource> getResources() {
return resources;
}

public void setResources(List<Resource> resources) {
    this.resources = resources;
}
}

**Comment by maoxianfly** [comment]
嗯，已经解决了，谢谢。
