### ISSUE TITLE
使用jprotobuf-precompile-plugin预编译生成的一个文件大小为0导致错误

### ISSUE THREAD

**Issue by yourwafer** [jhunters/jprotobuf#51]
这个错误
-rw-r--r--  1 wafer  staff     0  7 11 15:27 ResLoginInfo$$JProtoBufClass.class
-rw-r--r--  1 wafer  staff   973  7 11 15:27 ResLoginInfo.class
下面这个正常
-rw-r--r--  1 wafer  staff  3690  7 11 15:27 ResRandomName$$JProtoBufClass.class
-rw-r--r--  1 wafer  staff   761  7 11 15:27 ResRandomName.class
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
什么原因呢

**Comment by yourwafer** [comment]
嗯，我知道了，是继承的包在其他地方

但是package的时候怎么没报错输出

**Comment by jhunters** [comment]
能否提供一下有问题的代码ResRandomName和它继承的类的代码

**Comment by yourwafer** [comment]
代码没有问题，问题是这样
public class ResRandomName extends ResResult {}
`public class ResResult {

	/** 每个返回VO固定order */
	public static final int RES_RESULT_ORDER = 999;

	/** 通信处理成功 */
	public static final ResResult SUCCESS = ResResult.valueOf(ResultCode.SUCCESS);
	/** 通信处理发生未处理异常 */
	public static final ResResult UNKONWN = ResResult.valueOf(ResultCode.UNKNOWN_ERROR);

	/** 错误码 */
	@Protobuf(description = "错误码(字段的order默认固定为999)", order = RES_RESULT_ORDER, required = false)
	protected int code = ResultCode.SUCCESS;

	public final int getCode() {
		return code;
	}

	public static ResResult valueOf(int code) {
		ResResult r = new ResResult();
		r.code = code;
		return r;
	}
}`

这个ResResult在其他项目，作为公共包被很多其他项目依赖

**Comment by jhunters** [comment]
使用你给的类似代码测试没有发现你说的问题。
public class ResRandomName extends ResResult {

}

package test.test;

import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;

public class ResResult {
    /** 每个返回VO固定order */
    public static final int RES_RESULT_ORDER = 999;

    /** 通信处理成功 */
    public static final ResResult SUCCESS = ResResult.valueOf(1);
    /** 通信处理发生未处理异常 */
    public static final ResResult UNKONWN = ResResult.valueOf(2);

    /** 错误码 */
    @Protobuf(description = "错误码(字段的order默认固定为999)", order = RES_RESULT_ORDER, required = false)
    protected int code = 1;

    public final int getCode() {
        return code;
    }

    public static ResResult valueOf(int code) {
        ResResult r = new ResResult();
        r.code = code;
        return r;
    }
}

pom
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.baidu</groupId>
	<artifactId>jprotobuftest</artifactId>
	<version>0.0.1-SNAPSHOT</version>


	<dependencies>

		<dependency>
			<groupId>com.baidu</groupId>
			<artifactId>jprotobuf</artifactId>
			<version>1.9.8</version>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.baidu</groupId>
				<artifactId>jprotobuf-precompile-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<skipErrorNoDescriptorsFound>true</skipErrorNoDescriptorsFound>
					<filterClassPackage>test</filterClassPackage>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>precompile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by yourwafer** [comment]
我看了下你的源码，发现JprotobufPreCompileMain在编译错误的时候没有日志输出
`
try {
					List<Field> fields = FieldUtils.findMatchedFields(c, Protobuf.class);
					if (!fields.isEmpty()) {
						ProtobufProxy.create(c, false, outputPath);
					}
				} catch (Throwable e) {
				}
`
我加了e.printStackTrace()，就发现了下面的错误

Caused by: java.lang.IllegalStateException: Compilation failed. class: com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass, diagnostics: [FileDescriptorProtoPOJO$$JProtoBufClass.java:30: 错误: 找不到符号
size += CodedConstant.computeListSize(3,f_3, FieldType.STRING,false,ProtobufProxy.OUTPUT_PATH.get());
                                                                                 ^
  符号:   变量 OUTPUT_PATH
  位置: 类 com.baidu.bjf.remoting.protobuf.ProtobufProxy, FileDescriptorProtoPOJO$$JProtoBufClass.java:37: 错误: 找不到符号
size += CodedConstant.computeListSize(4,f_4, FieldType.OBJECT,false,ProtobufProxy.OUTPUT_PATH.get());
                                                                                 ^
  符号:   变量 OUTPUT_PATH
  位置: 类 com.baidu.bjf.remoting.protobuf.ProtobufProxy, FileDescriptorProtoPOJO$$JProtoBufClass.java:44: 错误: 找不到符号
size += CodedConstant.computeListSize(5,f_5, FieldType.OBJECT,false,ProtobufProxy.OUTPUT_PATH.get());

**Comment by jhunters** [comment]
请检查 一下你的jprotobuf版本，使用plugin有以下要求：

jprotobuf-precompile-plugin 支持maven编译时同时进行jprotobuf对象的预编译操作. 注：plugin版本建议使用>=1.2.0， jprotobuf 支持版本>=1.9.4

**Comment by yourwafer** [comment]
我对maven插件不熟悉，我在你源代码里改了输出的代码，发现它会去查找jprotobuf-1.8.2版本，于是我把本地1.8.2的包删掉，它还是会去下载，错误的原因在于1.8.2根本没用OUTPUT_PATH变量，导致错误
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/baidu/jprotobuf/1.8.2/jprotobuf-1.8.2.jar

**Comment by jhunters** [comment]
把你的pom.xml文件内容发我一下，我看是哪配置有问题?

**Comment by yourwafer** [comment]
已经找到问题了，我没有在本项目里面明确声明jprotobuf的版本，因为依赖的其它项目有加入进去。
于是我把
`
<dependency>
			<groupId>com.baidu</groupId>
			<artifactId>jprotobuf</artifactId>
			<version>1.9.8</version>
		</dependency>
`
加进去，precompile-plugin 添加的路径就变成1.9.8，这样问题就解决了。
所以，这是不是maven的bug啊，但问题是我就算没有明确声明jprotobuf版本，它也是去查找下载它依赖的正确版本啊，为什么是1.8.2

**Comment by jhunters** [comment]
这个也是maven使用需要注意的问题，plugin的依赖是没有dependency的依赖优先级高的

**Comment by yourwafer** [comment]
嗯，好的，谢谢你
只是希望你把那个编译错误的输出出来，或者编译失败就不用生成出来一个大小为0的文件。
