### ISSUE TITLE
log的问题

### ISSUE THREAD

**Issue by beykery** [jhunters/jprotobuf#61]
1.10.0版本
com.baidu.bjf.remoting.protobuf.utils.ProtobufProxyUtils.java
第148行的log
我觉得可以删掉，其实我们使用的时候，基本上从来都不指定order的，我看这不是什么问题。
@xiemalin

**Comment by jhunters** [comment]
这个log为了提醒一下没有使用Order后对应order， 很多使用者经常会忘记，在对象的属性中间加了一个属性，发现测试不过，有这个Log,可以快速定位问题
