### ISSUE TITLE
针对Protobuf v3 repeated float类型的字段序列化没有packed的问题

### ISSUE THREAD

**Issue by artern** [jhunters/jprotobuf#65]
Protobuf v3中所有类型的repeated字段都默认采用packed方式编码，而在v2时只针对增加了[packed=true]后缀的类型进行packed编码，在jprotobuf 2.0.4对repeated字段还是使用了非packed方式编码，造成通过Protobuf与jprotobuf所产生的repeated字段bytes互不识别

**Comment by jhunters** [comment]
packed 还没有支持，包括1.x版本

**Comment by artern** [comment]
Protobuf v3中默认所有类型的repeated字段都是packed了，对于v2应该只有使用了[packed=true]后缀才会有影响（这个特性应该很少用），而对v3会影响所有简单类型的repeated字段如repeated float。

**Comment by jhunters** [comment]
感谢反馈，关于具体 修复进展，请关注本issue，谢谢

**Comment by jhunters** [comment]
fix version 2.0.5。V3支持版本 已修复packed问题

**Comment by artern** [comment]
已经收到，谢谢

**Comment by artern** [comment]
额，还是有问题，例如：
`@Protobuf(fieldType = FieldType.INT32, order = 2)
private List<Integer> samples;`
当samples设置为：
`setSamples(Arrays.asList(62, 218, 254, 849, 288, 591, 277, 374, 318, 263, 244, 944, 220, 310, 751, 323,317, 497, 55, 635, 58, 962, 426, 597, 778, 685, 652, 614, 467, 554, 306, 581, 426, 831, 789, 613, 879,75, 312, 35, 710, 811, 200, 388, 16, 275, 386, 892, 554, 136, 163, 334, 475, 756, 579, 554, 977, 271,551, 547, 229, 62, 363, 22, 586, 622, 195, 168, 224, 837, 928, 857, 680, 880, 753, 500, 511, 610, 268,408, 298, 643, 500, 586, 220, 857, 525, 2, 892, 852, 824, 593, 846, 687, 283, 625, 984, 450, 468, 110))`
时序列化后再反序列化出错
`codec.decode(codec.encode(samplesTest));`

**Comment by jhunters** [comment]
应该是没有对list判空导致生成的内容多出来了，会尽快修复

**Comment by jhunters** [comment]
fixed at 2.0.6. please try again

**Comment by artern** [comment]
While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
好像还是不行

**Comment by jhunters** [comment]
https://github.com/jhunters/jprotobuf/blob/master/v3/src/test/java/com/baidu/bjf/remoting/protobuf/packed/PackedValueTest.java 这个根据你的情况测试的代码，难道没有覆盖其它场景吗？ 能否把你测试的代码发出来一下

**Comment by artern** [comment]
`
public static class LongListPO {
        
        @Protobuf(fieldType = FieldType.INT32, order = 2)
        private List<Integer> samples;
        
        public List<Integer> getSamples() {
            return samples;
        }
        
        public void setSamples(List<Integer> samples) {
            this.samples = samples;
        }
        
    }
    
    public static void main(String[] args) throws Exception {
        Codec<LongListPO> codec = ProtobufProxy.create(LongListPO.class);
        LongListPO sound = new LongListPO();
        sound.setSamples(Arrays.asList(62, 218, 254, 849, 288, 591, 277, 374, 318, 263, 244, 944, 220, 310, 751, 323,
                317, 497, 55, 635, 58, 962, 426, 597, 778, 685, 652, 614, 467, 554, 306, 581, 426, 831, 789, 613, 879,
                75, 312, 35, 710, 811, 200, 388, 16, 275, 386, 892, 554, 136, 163, 334, 475, 756, 579, 554, 977, 271,
                551, 547, 229, 62, 363, 22, 586, 622, 195, 168, 224, 837, 928, 857, 680, 880, 753, 500, 511, 610, 268,
                408, 298, 643, 500, 586, 220, 857, 525, 2, 892, 852, 824, 593, 846, 687, 283, 625, 984, 450, 468, 110));
        codec.decode(codec.encode(sound));
    }
`
应该是encode出的bytes无法被decode， 应该decode过程是正确的

**Comment by artern** [comment]
在list较短时则不会有问题
sound.setSamples(Arrays.asList(62, 218, 254));
可顺利将encode的内容decode

**Comment by jhunters** [comment]
找到问题并修复了 ，请先用这个版本吧 
https://oss.sonatype.org/content/repositories/snapshots//com/baidu/jprotobuf/2.0.7-SNAPSHOT/

**Comment by jhunters** [comment]
2.0.7 is out should fix the problem.

**Comment by artern** [comment]
用了段时间，没有再遇到类似的问题，这个可以close了，感谢
