### ISSUE TITLE
Stream和byte[] 两种方式的编解码不一致 bug

### ISSUE THREAD

**Issue by wjm0729** [jhunters/jprotobuf#79]
// 消息类:
public class LoginRequest {
    @Protobuf(fieldType = FieldType.INT64, order = 1)
    private long uid;
    @Protobuf(fieldType = FieldType.STRING, order = 2)
    private String userName;
    @Protobuf(fieldType = FieldType.STRING, order = 3)
    private String deviceId;
    @Protobuf(fieldType = FieldType.STRING, order = 4)
    private String appVersion;
    @Protobuf(fieldType = FieldType.STRING, order = 5)
    private String pf;
    @Protobuf(fieldType = FieldType.STRING, order = 6)
    private String lang;
    @Protobuf(fieldType = FieldType.INT32, order = 7)
    private int ptype = -2;
    @Protobuf(fieldType = FieldType.MAP, order = 8)
    private Map<String, String> params = Maps.newHashMap();
    @Protobuf(fieldType = FieldType.STRING, order = 9)
    private String zoneName;
   // get set...
}

//===================================================
//---------------------------测试代码----------------------------------
       LoginRequest loginInfo = new LoginRequest();
        loginInfo.setUserName("AAAAA");
        loginInfo.setDeviceId(IDGeneratorTest.uuid());
        loginInfo.setZoneName("S1");

        {
            // 方法1  Stream:
            ByteBuf buffer = Unpooled.buffer();
            ByteBufOutputStream output1 = new ByteBufOutputStream(buffer);
            CodedOutputStream output = CodedOutputStream.newInstance(output1, 0);
            ProtobufProxy.create(LoginRequest.class).writeTo(loginInfo, output);
            LoginRequest loginInfo1 = ProtobufProxy.create(LoginRequest.class).readFrom(CodedInputStream.newInstance(new ByteBufInputStream(output1.buffer())));

            System.err.println("test1:" + JSON.toJSONString(loginInfo1));
        }

        {
            // 方法2  byte[]:
            byte[] data = ProtobufProxy.create(LoginRequest.class).encode(loginInfo);
            LoginRequest loginInfo2 = ProtobufProxy.create(LoginRequest.class).decode(data);

            System.err.println("test2:" + JSON.toJSONString(loginInfo2));
        }

// =================输出====================
test1:{"deviceId":"5ccbaed5c1ad49768953fdf3330df500","params":{},"ptype":-2,"uid":0,"userName":"AAAAA"}
test2:{"deviceId":"5ccbaed5c1ad49768953fdf3330df500","params":{},"ptype":-2,"uid":0,"userName":"AAAAA","zoneName":"S1"}

用stream方式 zoneName 字段没了 ...

**Comment by jhunters** [comment]
应该是测试的代码有问题，以下的测试代码，用readFrom 没有问题
        LoginRequest loginInfo = new LoginRequest();
        loginInfo.setUserName("AAAAA");
        loginInfo.setDeviceId("111111");
        loginInfo.setZoneName("S1");

        byte[] data = ProtobufProxy.create(LoginRequest.class).encode(loginInfo);
        LoginRequest loginInfo2 = ProtobufProxy.create(LoginRequest.class).decode(data);

        System.err.println("test2:" + loginInfo2);
       //  使用readFrom解析
        loginInfo2 = ProtobufProxy.create(LoginRequest.class)
                .readFrom(CodedInputStream.newInstance(data));
        
        System.err.println("test2:" + loginInfo2);

**Comment by wjm0729** [comment]
用  byte[] 是没问题的.  
求帮忙写一个用 netty  Bytebuf 编解码的例子.
因为这样可以使用netty的内存池, 省去了new byte[] . GC负担小.

**Comment by wjm0729** [comment]
/**
     * Write object to byte array by {@link FieldType}.
     *
     * @param out the out
     * @param order the order
     * @param type the type
     * @param o the o
     * @param list the list
     * @param withTag the with tag
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static void writeObject(CodedOutputStream out, int order, FieldType type, Object o, boolean list,
            boolean withTag) throws IOException {
        if (o == null) {
            return;
        }

        if (type == FieldType.OBJECT) {

            Class cls = o.getClass();
            Codec target = ProtobufProxy.create(cls);

            if (withTag) {
                out.writeRawVarint32(makeTag(order, WireFormat.WIRETYPE_LENGTH_DELIMITED));
            }
            out.writeRawVarint32(target.size(o));

            target.writeTo(o, out);

            // 这里少了一个 out.flush();

            return;
        }

**Comment by jhunters** [comment]
是要这个例子吗？ 
       ByteBuf wrappedBuffer = Unpooled.wrappedBuffer(data);
        loginInfo2 = ProtobufProxy.create(LoginRequest.class)
                .readFrom(CodedInputStream.newInstance(wrappedBuffer.array()));
        
        System.err.println("test2:" + loginInfo2);

**Comment by wjm0729** [comment]
`{
            // 方法1  Stream:
            ByteBuf buffer = Unpooled.buffer();

            CodedOutputStream output = CodedOutputStream.newInstance(new ByteBufOutputStream(buffer), 64);
            ProtobufProxy.create(LoginRequest.class).writeTo(loginInfo, output);
            output.flush();

            LoginRequest loginInfo1 = ProtobufProxy.create(LoginRequest.class).readFrom(CodedInputStream.newInstance(new ByteBufInputStream(buffer)));
            System.err.println("test1:" + JSON.toJSONString(loginInfo1));
        }`

**Comment by wjm0729** [comment]
这样就好了.

**Comment by jhunters** [comment]
对使用readFrom与writeTo， 流的flush行为需要你自行控制，包装关闭操作也是
