### ISSUE TITLE
BUG反馈，当POJO在根目录下时会报错

### ISSUE THREAD

**Issue by monkey1993** [jhunters/jprotobuf#81]
java.lang.IllegalStateException: Failed to compile class, cause: .StringTypePOJOClass$$JProtoBufClass, class: .StringTypePOJOClass$$JProtoBufClass, code:

其中 .StringTypePOJOClass$$JProtoBufClass 这个 class 的名字明显有问题

**Comment by jhunters** [comment]
目前该 问题在最新版本已经修改了，请用新的版本
