### ISSUE TITLE
子类继承父类，如果order从51开始，则会报错

### ISSUE THREAD

**Issue by monkey1993** [jhunters/jprotobuf#89]
父类中，order为1-5，子类中如果order从6开始不会报错，从50开始也不会报错，但是，从51开始，则会报错：
com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 34, limit: 33, len: 1

**Comment by jhunters** [comment]
使用的版本号能否发出来一下？

**Comment by monkey1993** [comment]
现在用的是2.1.11版本，很奇怪的问题，有时候从50开始，也会报错，从51开始，报错的可能性变大很多，我也正在找问题呢

**Comment by monkey1993** [comment]
父类 字段如下：
	@Protobuf(fieldType = FieldType.INT64, order = 1, description = "玩家ID")
	private long playerId;

	@Protobuf(fieldType = FieldType.INT64, order = 2, description = "物品唯一ID")
	private long sequenceId;

	@Protobuf(fieldType = FieldType.INT32, order = 3, description = "物品ID, 这个ID并不是唯一存在的")
	private int itemId;

	@Protobuf(fieldType = FieldType.INT32, order = 4, description = "物品数量")
	private int itemCount;
子类字段如下：
	@Protobuf(fieldType = FieldType.INT32, order = 51, description = "等级")
	private int unitLvl;

	@Protobuf(fieldType = FieldType.INT32, order = 52, description = "当前经验")
	private int unitExp;

	@Protobuf(fieldType = FieldType.INT32, order = 53, description = "技能等级")
	private List<Integer> skillLevels;

	@Protobuf(fieldType = FieldType.INT32, order = 54, description = "成长值")
	private List<Integer> grownWeight;

	@Protobuf(fieldType = FieldType.INT32, order = 55, description = "资质")
	private int grownId;
数据json：
{"attr":{"attr":[36850,6,0,2,2750,2400,10000,0,0,0,0,9500,500,500,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"lifeProportion":0.0},"grownId":1,"grownWeight":[100,100,100],"itemCount":1,"itemId":60104,"itemType":"UnitType","playerId":162,"roleDict":{"atkAdd":350,"attr":{"attr":[32000,6,0,2,2400,2100,10000,0,0,0,0,9500,500,500,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"lifeProportion":0.0},"defAdd":300,"growthFactorByGrownIdMap":{1:{"grown":1.0,"grownId":1,"weight":100}},"growthFactorByWeightMap":{100:{"$ref":"$.roleDict.growthFactorByGrownIdMap[1]"}},"id":60104,"itemType":"UnitType","lifeAdd":4850,"lvlup":-1,"sex":2,"skillList":[2010,2011,2012,2013],"speedAdd":0,"type":0},"sequenceId":1,"skillLevels":[0,0,0,0],"unitExp":0,"unitLvl":1}
可以稳定复现。

**Comment by monkey1993** [comment]
复现不出来，可以加我QQ，272174722

**Comment by jhunters** [comment]
2.x版本会再发布一个版本，应该会修改这个问题

**Comment by jhunters** [comment]
2.2.0版本已经发布，可以使用这个版本解决

**Comment by monkey1993** [comment]
方便加一下QQ么，跟踪远吗发现了一个问题...

**Comment by monkey1993** [comment]
详见CodedConstant.java第350行，在这里写死了一个 `size += 1;`应该就是这里的问题，51序列化出来，应该是占两个byte，-86和3，这里写死了一个，造成在最后边少了一个~望修复~

**Comment by monkey1993** [comment]
呃，错了，是53，我打字的时候，脑抽了...
