### ISSUE TITLE
不支持数组 Array序列化？

### ISSUE THREAD

**Issue by tidus5** [jhunters/jprotobuf#94]
`Exception in thread "main" java.lang.RuntimeException: Array type of field 'testArray' on class 'test.SimpleTypeTest' is not support,  please use List instead.
	at com.baidu.bjf.remoting.protobuf.utils.ProtobufProxyUtils.processDefaultValue(ProtobufProxyUtils.java:96)
`

version  2.2.4

**Comment by xiemalin** [comment]
数组不支持， 请用List就可以了
