### ISSUE TITLE
enum序列化新添加类型，反序列化不存在该类型，抛出异常

### ISSUE THREAD

**Issue by chinaken** [jhunters/jprotobuf#95]
如果在enum新增类型，反序列中没有该类型，则抛出异常
Caused by: java.lang.IllegalArgumentException: No enum constant

可否设置不存在，反序列到一个默认值

**Comment by xiemalin** [comment]
的确， protobuf的处理是值不到，返回的是null. 
该问题下一个版本修复，请关注

**Comment by jhunters** [comment]
fixed at  1.11.4 & 2.2.5
