### ISSUE TITLE
jprotobuf-protoparser

### ISSUE THREAD

**Issue by drtrang** [jhunters/jprotobuf#96]
```xml
<dependency>
    <groupId>com.baidu</groupId>
    <artifactId>jprotobuf-protoparser</artifactId>
    <version>1.0.1</version>
<dependency>
```
请问这个项目是你维护的吗？Github 上没有找到源码……
在用这个工具的时候，碰到几个 case：
1. ProtoParser 无法解析 reserved 关键字
2. ProtoParser 无法解析 stream 关键字

**Comment by xiemalin** [comment]
https://github.com/square/protoparser  项目链接。 目前的确没能支持最新的关键识别了
